print('this file was created within RStudio')
print('And now it lives on GitHub')
print('change 1')
print('change 2')
print('change 3')
print('Change done from GitHub')
print ('change done in RStudio while there is another change done in GitHub')